services:


  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      NIFI_WEB_HTTPS_PORT: 8443
    depends_on:
      - cassandra
      - zookeeper
      - streaming_simulation
      - kafka
    networks:
      custom_net:
        ipv4_address: 192.168.1.102
    # volumes:
    #   - ./services/nifi/conf:/opt/nifi/nifi-current/conf
    #   - ./services/nifi/nar_extensions:/opt/nifi/nifi-current/nar_extensions
    #   - ./services/nifi/extensions:/opt/nifi/nifi-current/extensions
    

  streaming_simulation:
    image: docker.io/library/streaming_simulation:latest
    container_name: streaming_simulation
    networks:
      custom_net:
        ipv4_address: 192.168.1.101
    ports:
      - "5001:5001"
    restart: unless-stopped


  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    networks:
      custom_net:
        ipv4_address: 192.168.1.103
    environment:
      CASSANDRA_CLUSTER_NAME: "NifiCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_SEEDS: "cassandra"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.105:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      custom_net:
        ipv4_address: 192.168.1.105


  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      custom_net:
        ipv4_address: 192.168.1.104

  
networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
