services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443" 
    networks:
      custom_net:
        ipv4_address: 192.168.1.100
    environment:
      - NIFI_WEB_HTTP_PORT=8443
    volumes:
      - ./services/nifi/conf:/opt/nifi/nifi-current/conf
    restart: unless-stopped

  streaming_simulation:
    image: docker.io/library/streaming_simulation:latest
    container_name: streaming_simulation
    networks:
      custom_net:
        ipv4_address: 192.168.1.101
    ports:
      - "5000:5000"
    restart: unless-stopped

  hive:
    image: apache/hive:4.0.0
    container_name: hive
    ports:
      - "10000:10000" 
      - "10002:10002"
    networks:
      custom_net:
        ipv4_address: 192.168.1.102
    environment:
      - SERVICE_NAME=hiveserver2
    restart: unless-stopped
    command: >
      /opt/hive/bin/hive --service hiveserver2
    volumes:
      - ./services/hive/conf:/opt/hive/conf
      - ./services/hive/tez/conf:/opt/hive/tez/conf

  metastore-standalone:
    image: apache/hive:4.0.0
    container_name: metastore-standalone
    ports:
      - "9083:9083"
    networks:
      custom_net:
        ipv4_address: 192.168.1.103
    environment:
      - SERVICE_NAME=metastore
    restart: unless-stopped
    command: >
      /opt/hive/bin/hive --service metastore
    volumes:
      - ./services/hive-metastore/conf:/opt/hive/conf
      - ./services/hive-metastore/tez/conf:/opt/hive/tez/conf

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
