services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443" 
    networks:
      custom_net:
        ipv4_address: 192.168.1.100
    environment:
      - NIFI_WEB_HTTP_PORT=8443
    restart: unless-stopped
  streaming_simulation:
    image: docker.io/library/streaming_simulation:latest
    container_name: streaming_simulation
    networks:
      custom_net:
        ipv4_address: 192.168.1.101
    ports:
      - "5000:5000"
    restart: unless-stopped
networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24