services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080" 
      - "5000:5000" 
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    restart: unless-stopped
