name: tests
on:
  pull_request:
    branches:
      - main
jobs:

  test-processing-simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.13.0 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./services/streaming_processing/streaming_processing_requirements.txt
          pip install -r ./services/streaming_simulation/streaming-requirements.txt
      - name: Run tests
        run: |
          pytest ./services/streaming_simulation ./services/streaming_processing

  test-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./services/batch_processing/batch_processing_requirements.txt
      - name: Run tests
        run: |
          pytest ./services/batch_processing